version: "3"
services:
  source_db:
    image: "postgres:11"
    container_name: postgresDb1
    ports:
    - "54320:5432"
    volumes:
    - my_dbdata:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=root
  target_db:
    image: "postgres:11"
    container_name: postgresDb2
    ports:
      - "5433:5432"
    volumes:
      - my_dbdata2:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root
volumes:
  my_dbdata:
  my_dbdata2:
