version: "3"
services:
  source_db:
    image: "postgres:11"
    container_name: "my_postgres_1"
    ports:
      - "54320:5432"
    volumes:
      - my_pg1:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root
  target_db:
    image: "postgres:11"
    container_name: "my_postgres_2"
    ports:
      - "5433:5432"
    volumes:
      - my_pg2:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root
  airflow:
    image: puckel/docker-airflow
    container_name: "airflow"
    ports:
      - "8082:8080"
    environment:
      - PYTHONPATH=/usr/local/airflow/operators/
    volumes:
      - ./airflow:/usr/local/airflow
    command: webserver
volumes:
  my_pg1:
  my_pg2:
